(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/form/receive_way"],{"29a0":function(n,t,e){"use strict";e.r(t);var o=e("e250"),a=e.n(o);for(var i in o)"default"!==i&&function(n){e.d(t,n,(function(){return o[n]}))}(i);t["default"]=a.a},"6df6":function(n,t,e){},"852a":function(n,t,e){"use strict";var o;e.d(t,"b",(function(){return a})),e.d(t,"c",(function(){return i})),e.d(t,"a",(function(){return o}));var a=function(){var n=this,t=n.$createElement;n._self._c},i=[]},"93e8":function(n,t,e){"use strict";var o=e("6df6"),a=e.n(o);a.a},d617:function(n,t,e){"use strict";e.r(t);var o=e("852a"),a=e("29a0");for(var i in a)"default"!==i&&function(n){e.d(t,n,(function(){return a[n]}))}(i);e("93e8");var u,c=e("f0c5"),r=Object(c["a"])(a["default"],o["b"],o["c"],!1,null,"b518643e",null,!1,o["a"],u);t["default"]=r.exports},e250:function(n,t,e){"use strict";(function(n){Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var o=function(){e.e("components/wyb-transition/wyb-transition").then(function(){return resolve(e("54a7"))}.bind(null,e)).catch(e.oe)},a=function(){e.e("components/form/total").then(function(){return resolve(e("52b6"))}.bind(null,e)).catch(e.oe)},i={name:"receive_way",components:{Total:a,Transition:o},onLoad:function(){this.tab(0)},data:function(){return{array:["🇲🇴 澳門旗艦店","🇨🇳 中國大陸店"],array2:["🇲🇴 +853","🇨🇳 +86"],index:0,type:0,copy:!1,typeList:["fade","slide-up"],customerInfo:{name:"",areaCodeIndex:"",number:"",email:""}}},mounted:function(){},methods:{tab:function(n){this.type=n},bindPickerChange:function(n){this.index=n.detail.value},copyInfo:function(){var t=this;this.copy=!this.copy,this.copy&&(n.showLoading({title:"同步中"}),setTimeout((function(){n.hideLoading(),t.customerInfo=n.getStorageSync("customerInfo")||t.customerInfo,t.index=t.customerInfo.areaCodeIndex||0}),500))}}};t.default=i}).call(this,e("543d")["default"])}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/form/receive_way-create-component',
    {
        'components/form/receive_way-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("d617"))
        })
    },
    [['components/form/receive_way-create-component']]
]);
